package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Light Mode Premium Monochrome Palette
val PremiumPrimaryLight = Color(0xFF111112)
val PremiumOnPrimaryLight = Color(0xFFFFFFFF)
val PremiumBackgroundLight = Color(0xFFF3F3F5)
val PremiumOnBackgroundLight = Color(0xFF111112)
val PremiumSurfaceLight = Color(0xFFFFFFFF)
val PremiumOnSurfaceLight = Color(0xFF111112)
val PremiumSurfaceVariantLight = Color(0xFFEBEBEF)
val PremiumOnSurfaceVariantLight = Color(0xFF4E4E54)
val PremiumOutlineLight = Color(0xFFDBDBE1)
val PremiumSecondaryLight = Color(0xFF45454B)
val PremiumOnSecondaryLight = Color(0xFFFFFFFF)
val PremiumSecondaryContainerLight = Color(0xFFEBEBEF)
val PremiumOnSecondaryContainerLight = Color(0xFF111112)
val PremiumTertiaryLight = Color(0xFF2C2C2E)
val PremiumOnTertiaryLight = Color(0xFFFFFFFF)
val PremiumTertiaryContainerLight = Color(0xFFF3F3F5)
val PremiumOnTertiaryContainerLight = Color(0xFF111112)

// Dark Mode Premium Obsidian Palette
val PremiumPrimaryDark = Color(0xFFFFFFFF)
val PremiumOnPrimaryDark = Color(0xFF111112)
val PremiumBackgroundDark = Color(0xFF0C0C0D)
val PremiumOnBackgroundDark = Color(0xFFF5F5F7)
val PremiumSurfaceDark = Color(0xFF17171A)
val PremiumOnSurfaceDark = Color(0xFFFFFFFF)
val PremiumSurfaceVariantDark = Color(0xFF242428)
val PremiumOnSurfaceVariantDark = Color(0xFF9898A0)
val PremiumOutlineDark = Color(0xFF333338)
val PremiumSecondaryDark = Color(0xFF8A8A93)
val PremiumOnSecondaryDark = Color(0xFF111112)
val PremiumSecondaryContainerDark = Color(0xFF242428)
val PremiumOnSecondaryContainerDark = Color(0xFFFFFFFF)
val PremiumTertiaryDark = Color(0xFFEBEBEF)
val PremiumOnTertiaryDark = Color(0xFF111112)
val PremiumTertiaryContainerDark = Color(0xFF1E1E22)
val PremiumOnTertiaryContainerDark = Color(0xFFFFFFFF)

// Ash Theme (Slate Ash Palette)
val AshPrimary = Color(0xFF343438)
val AshOnPrimary = Color(0xFFFFFFFF)
val AshPrimaryContainer = Color(0xFFD4D4DC)
val AshOnPrimaryContainer = Color(0xFF232326)
val AshSecondary = Color(0xFF5A5A62)
val AshOnSecondary = Color(0xFFFFFFFF)
val AshSecondaryContainer = Color(0xFFE8E8EC)
val AshOnSecondaryContainer = Color(0xFF2C2C30)
val AshTertiary = Color(0xFF4E4E54)
val AshOnTertiary = Color(0xFFFFFFFF)
val AshTertiaryContainer = Color(0xFFE2E2E6)
val AshOnTertiaryContainer = Color(0xFF2C2C30)
val AshBackground = Color(0xFFDEDEE3)
val AshOnBackground = Color(0xFF232326)
val AshSurface = Color(0xFFECECEF)
val AshOnSurface = Color(0xFF232326)
val AshSurfaceVariant = Color(0xFFD8D8DF)
val AshOnSurfaceVariant = Color(0xFF4C4C52)
val AshOutline = Color(0xFFB0B0B8)

